#!/bin/bash

# fail if anything goes wrong
set -e

# get the directory this file is stored in
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# push current directory onto stack
# and move to this file's directory
pushd $DIR

# move up to the parent and down into docs
cd ../docs

# remove our existing docs
rm -rf build/*

# run our makefile
make html


# return our path to its original state
popd

